highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: ANKUSH JAIN
email: jainankush822@gmail.com
description: Website of ANKUSH JAIN, Shivajirao Kadam Institute of Engineering and Management
keywords: Ankush,Jain, 49ku5h,  security, developer, geek, programmer, github
baseurl: ""
url: http://ankushjain.xyz
name: 49ku5h\'s blog
author:
  name: ANKUSH JAIN
