github_url: https://github.com/49ku5h
twitter_url: https://twitter.com/49ku5h
linkedin_url: https://in.linkedin.com/in/ankush-jain-792279167/
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf
sitemap_url: /sitemap.xml
